// 도트 스프라이트. 한 글자가 한 도트이고, 한 그림의 모든 줄은 길이가 같아야 합니다.

export const SPRITES = {
  // ── 영웅 16×16 ──────────────────────────────
  warrior: [
    ".......rr.......",
    "......rRr.....k.",
    ".....kkkkkk..kwk",
    "....kggggggk.kgk",
    "....kgwggggk.kgk",
    "....kkkkkkkk.kgk",
    "....kssssssk.kgk",
    "....kskssksk.kgk",
    "....kSssssSkkyyk",
    ".kkk.kkkkkkkkksk",
    "kuuuk.uuuuukkksk",
    "kuyukuuyuuuk.kk.",
    "kyyykbbbbbbk....",
    "kuyuk.kuuuk.....",
    ".kuk..kGkGk.....",
    "..k..kkk.kkk....",
  ],
  rogue: [
    "................",
    "......kkkk......",
    ".....kLLLLk.....",
    "....kLLLLLLk....",
    "....kLKKKKLk....",
    "....kKssssKk....",
    "....kskssksk....",
    "....kLLLLLLk....",
    "...kLLmLLmLLk...",
    "..kLLkLLLLkLLk..",
    "..ksk.kLLk.ksk..",
    ".kgk..kbyk..kgk.",
    "kwk...kLLk...kwk",
    "k.....kmmk.....k",
    "......kk.kk.....",
    ".....kBk.kBk....",
  ],
  mage: [
    ".......k........",
    "......kpk.....k.",
    ".....kppPk...kck",
    ".....kpyPk...kck",
    "....kppppPk...k.",
    "..kkkkkkkkkkk.b.",
    "....kssssssk..b.",
    "....kskssksk..b.",
    "....kwwwwwwk..b.",
    "...kpwwwwwwpk.b.",
    "..kppkwwwwkppksk",
    "..kpppkwwkpppkb.",
    "..kppppyypppk.b.",
    "..kpppppppppk.b.",
    "...kPPPPPPPk..b.",
    "...kkkkkkkkk..k.",
  ],
  bard: [
    "...........y....",
    "..........yo....",
    ".....kkkkkok....",
    "....krrrrrrk....",
    "...kkkkkkkkkk...",
    "....kssssssk....",
    "....kskssksk....",
    "....ksssSssk....",
    ".....kkkkkk.....",
    "...krrwwwwrrk...",
    "..krrkrwwrkrrk..",
    "..kskbnnnnbkskk.",
    "...kbnnkknnbbbbk",
    "...kbnnkknnbk.k.",
    "....kbnnnnbk....",
    ".....kBk.kBk....",
  ],

  // ── 몬스터 ───────────────────────────────────
  slime: [
    "................",
    "................",
    "................",
    "................",
    "......kkkk......",
    "....kkeeeekk....",
    "...keewweeeek...",
    "..keewweeeeeek..",
    "..keeeeeeeeeek..",
    ".keekkeeeekkeek.",
    ".keekkeeeekkeek.",
    ".keeeeeeeeeeeek.",
    ".kleeeekkeeeelk.",
    ".klleeeeeeeellk.",
    ".kllllllllllllk.",
    "..kkkkkkkkkkkk..",
  ],
  wolf: [
    "................",
    "................",
    "................",
    "...k.k..........",
    "..kgkgk.........",
    "..kgggGk........",
    ".kgrggGGkkkkk.k.",
    "kwwggGGGGGGGGkgk",
    ".kkkwgGGGGGGGGGk",
    "....kwGGGGGGGGk.",
    "....kgGGkkkkGGk.",
    "...kgkGk...kGkGk",
    "...kgkGk...kGkGk",
    "...kwkwk...kwkwk",
    "...kk.kk...kk.kk",
    "................",
  ],
  goblin: [
    "................",
    "................",
    ".k....kkkk....k.",
    ".kek.keeeek.kek.",
    "..keekeeeekeek..",
    "...kkeyeeyekk...",
    ".....keeeek.....",
    ".....kwkkwk.....",
    "....kkekkekk....",
    "...keBbbbbBek...",
    "..kekBbbbbBkek..",
    "..kek.kBBk.kek..",
    ".kgk..kbbk..k...",
    "kwk...keek......",
    "k.....kekek.....",
    "......kk.kk.....",
  ],
  mimic: [
    "................",
    "................",
    "..kkkkkkkkkkkk..",
    ".kbbnbbbbbbnbbk.",
    ".kbbnbrbbrbnbbk.",
    ".kyyyyyyyyyyyyk.",
    ".kwkwkwkwkwkwkk.",
    ".kRRRRffffRRRRk.",
    ".kRRRffffffRRRk.",
    ".kRRRRRffRRRRRk.",
    ".kwkwkwkwkwkwkk.",
    ".kyyyyyyyyyyyyk.",
    ".kbbnbbyybbnbbk.",
    ".kbbnbbkkbbnbbk.",
    ".kbbnbbbbbbnbbk.",
    "..kkkkkkkkkkkk..",
  ],
  dragon: [
    "..............k.........",
    ".............kRk....k...",
    "...k...k....kRRRk..kRk..",
    "..kyk.kyk..kRrrRRkkRRk..",
    "..kyk.kyk.kRrrrrRRRRRRk.",
    ".krrrkrrrkRrrrrrrrrRRRk.",
    "krrrrrrrrkRrrrrrrrrrRRk.",
    "krwkrrrrrrkRrrrrrrrRRk..",
    "krkkrrrrrrkkRRrrrrRRk...",
    "krrrrrrrrrrk.kRRRRRk....",
    ".kyyyyyrrrrrk..kkkkk....",
    "..kkkkkyrrrrrkk.........",
    "......kyyrrrrrrk........",
    ".....kyyyrrrrrrrk.......",
    ".....kyyyyrrrrrrrk......",
    "....kyyyyyrrrrrrrrk.....",
    "....kyyyyyrrkrrrrrrk..k.",
    "....kyyyyrrrk.krrrrrkkrk",
    "...kryyyyrrrk.krrrrrrrrk",
    "..krrkyyrrrk...kkrrrrrk.",
    "..kwkwkkrrk......kkkkk..",
    "..kk.kwkwk..............",
    "......kk.k..............",
    "........................",
  ],

  // ── 소품 ─────────────────────────────────────
  lantern: [
    "...kkk..",
    "..k...k.",
    "..kkkkk.",
    ".kyyyyyk",
    ".kyYYYyk",
    ".kyYwYyk",
    ".kyYYYyk",
    ".kyyyyyk",
    "..kkkkk.",
    "...kkk..",
  ],
  heart: [
    ".kk.kk.",
    "krrkrrk",
    "krwrrrk",
    "krrrrrk",
    ".krrrk.",
    "..krk..",
    "...k...",
  ],
  heartEmpty: [
    ".kk.kk.",
    "kHHkHHk",
    "kHHHHHk",
    "kHHHHHk",
    ".kHHHk.",
    "..kHk..",
    "...k...",
  ],
  potion: [
    "..kkk..",
    "..knk..",
    ".kk.kk.",
    "kffwffk",
    "kfffffk",
    "kRfffRk",
    ".kkkkk.",
  ],
  coin: [
    ".kkkk.",
    "kyyYyk",
    "kyykyk",
    "kyykyk",
    "kooyok",
    ".kkkk.",
  ],
  d20: [
    ".........k.........",
    ".......kkHkk.......",
    ".....kkggHggkk.....",
    "...kkgggHwHgggkk...",
    ".kkgggggHwHgggggkk.",
    "kggggggHwwwHggggggk",
    "kHggggHwwwwwHggggHk",
    "kHgggHwwwwwwwHgggHk",
    "kHgggHwwwwwwwHgggHk",
    "kgggHwwwwwwwwwHgggk",
    "kggHwwwwwwwwwwwHggk",
    "kggHwwwwwwwwwwwHggk",
    "kHHwwwwwwwwwwwwwHHk",
    "kHHHHHHHHHHHHHHHHHk",
    ".kkGHGGGGGGGGGHGkk.",
    "...kkHGGGGGGGHkk...",
    ".....kkGGGGGkk.....",
    ".......kkGkk.......",
    ".........k.........",
  ],

  // ── 배경 스탬프 ──────────────────────────────
  pine: [
    "....kk....",
    "...kLLk...",
    "...kLLk...",
    "..kLlLLk..",
    "..kLLLLk..",
    ".kLlLLLLk.",
    "..kLLlLk..",
    ".kLLLLLLk.",
    "kLlLLLLLLk",
    ".kLLLlLLk.",
    "kLLLLLLlLk",
    "kLlLLLLLLk",
    ".kkkbbkkk.",
    "....bb....",
    "....bb....",
    "...kBBk...",
  ],
  pineDark: [
    "....kk....",
    "...kmmk...",
    "...kmmk...",
    "..kmLmmk..",
    "..kmmmmk..",
    ".kmLmmmmk.",
    "..kmmLmk..",
    ".kmmmmmmk.",
    "kmLmmmmmmk",
    ".kmmmLmmk.",
    "kmmmmmmLmk",
    "kmLmmmmmmk",
    ".kkkBBkkk.",
    "....BB....",
    "....BB....",
    "...kBBk...",
  ],
  oak: [
    "...kkkkkk...",
    ".kklllllLkk.",
    "kllelllLLLLk",
    "klelllllLLLk",
    "kllllLLllLLk",
    ".klllLLLLLk.",
    "kLllLLLLLLLk",
    ".kLLLkkLLLk.",
    "..kkk.bb.k..",
    "......bb....",
    "......bb....",
    ".....bBBb...",
  ],
  bush: [
    "..kkk.kk.",
    ".klelklLk",
    "kllllllLk",
    "kLlllLLLk",
    ".kkkkkkk.",
  ],
  rock: [
    "..kkkk.",
    ".kgggGk",
    "kggGGGk",
    "kGGGGHk",
    ".kkkkk.",
  ],
  tuft: [
    "l.l",
    "Ll.",
  ],
  mushroom: [
    ".kkk.",
    "krwrk",
    "kkkkk",
    ".kwk.",
  ],
  reeds: [
    ".b..b",
    ".B..b",
    "kl.kl",
    ".l..l",
    ".lk.l",
    "l.l.l",
    "l.lll",
  ],
  lily: [
    ".kkk.",
    "kllek",
    ".kkk.",
  ],
  moon: [
    "..kkk.",
    ".kYYYk",
    "kYYw.k",
    "kYY...",
    "kYYw.k",
    ".kYYYk",
  ],
  torch: [
    ".o.",
    "oyo",
    "yYy",
    "kbk",
    ".b.",
    ".b.",
    ".B.",
  ],
  flame: [
    "...o...",
    "..oyo..",
    ".oyYyo.",
    ".oyYyo.",
    "oyYwYyo",
    "oyYYYyo",
  ],
  campLogs: [
    "kbbkkbbk",
    ".kBbbBk.",
    "kbbkkbbk",
  ],
  tent: [
    ".......k........",
    "......krk.......",
    ".....krrRk......",
    "....krrrRRk.....",
    "...krrrkRRRk....",
    "..krrrkKkRRRk...",
    ".krrrkKKKkRRRk..",
    "krrrkKKKKKkRRRk.",
    "kkkkkkkkkkkkkkkk",
  ],
  barrel: [
    ".kkkkk.",
    "kbnbnbk",
    "kGGGGGk",
    "kbnbnbk",
    "kbnbnbk",
    "kGGGGGk",
    "kbnbnbk",
    ".kkkkk.",
  ],
  table: [
    "kkkkkkkkkkkkkk",
    "knnnnnnnnnnnnk",
    "kbbbbbbbbbbbbk",
    ".kbk......kbk.",
    ".kbk......kbk.",
    ".kBk......kBk.",
  ],
  mug: [
    "www..",
    "kyyk.",
    "kyykk",
    "kyyk.",
  ],
  candle: [
    ".o.",
    ".y.",
    "kwk",
    "kwk",
    "kkk",
  ],
  bottle: [
    ".k.",
    "kuk",
    "kuk",
    "kuk",
  ],
  bottleRed: [
    ".k.",
    "krk",
    "krk",
    "krk",
  ],
  keeper: [
    "....kkkkk...",
    "...kbbbbbk..",
    "...kssssk...",
    "...kskssk...",
    "...kBBBBk...",
    "..kkBsSBkk..",
    ".kwwkBBkwwk.",
    ".kswwwwwwsk.",
    ".kwwwwwwwwk.",
    "..kwwwwwwk..",
  ],
  elder: [
    "...kkkk...",
    "..kgggGk..",
    "..kssssk..",
    "..ksksk...",
    "..kwwwwk..",
    ".kUwwwwUk.",
    "kUUkwwkUUk",
    "kUUUUUUUUk",
    "kUUUUUUUUk",
    "kUUUUUUUUk",
    ".kUUUUUUk.",
    ".kkk..kkk.",
  ],
  chest: [
    ".kkkkkkkkkk.",
    "kbbnbbbbnbbk",
    "kbbnbbbbnbbk",
    "kyyyyyyyyyyk",
    "kbbnbyybnbbk",
    "kbbnbkkbnbbk",
    "kbbnbbbbnbbk",
    ".kkkkkkkkkk.",
  ],
  goldPile: [
    "....kyk...",
    "..kyyYyk..",
    ".kyoyyyyk.",
    "kyyyyoyYyk",
  ],
  bones: [
    "w.....w",
    ".wwwww.",
    "w.....w",
  ],
  skull: [
    ".kkk.",
    "kwwwk",
    "kkwkk",
    ".kwk.",
  ],
  crystal: [
    "..k..",
    ".kck.",
    ".kck.",
    "kcwck",
    "kccck",
    "kcUck",
    ".kkk.",
  ],
  stalactite: [
    "kHHHk",
    ".kHk.",
    ".kHk.",
    "..k..",
  ],
  house: [
    "......kk......",
    ".....kRRk.....",
    "....kRrrRk....",
    "...kRrrrrRk...",
    "..kRrrrrrrRk..",
    ".kRrrrrrrrrRk.",
    "kkkkkkkkkkkkkk",
    ".kaAaaaaaaAak.",
    ".kaykyaaakbak.",
    ".kaykyaaakbak.",
    ".kaaaaaaakbak.",
    ".kAAAAAAAkbAk.",
    ".kkkkkkkkkkkk.",
  ],
  lampPost: [
    "..kkk..",
    ".kyYyk.",
    ".kyYyk.",
    "..kkk..",
    "...k...",
    "...k...",
    "...k...",
    "...k...",
    "...k...",
    "...k...",
    "..kkk..",
  ],
  sword: [
    "..k..",
    ".kwk.",
    ".kwk.",
    ".kgk.",
    ".kwk.",
    ".kgk.",
    ".kwk.",
    "kkkkk",
    "kyyyk",
    "kkbkk",
    "..b..",
    "..y..",
  ],
  flower: [
    ".f.",
    "fYf",
    ".l.",
    "Ll.",
  ],
  grave: [
    "..kkkk..",
    ".kggggk.",
    "kggGGggk",
    "kgGggGgk",
    "kggGGggk",
    "kgggggGk",
    "kgggggGk",
    "kkkkkkkk",
  ],
  sign: [
    ".kkkkkkkkk.",
    "knnnnnnnnnk",
    "knbnbbnbbnk",
    ".kkkkbkkkk.",
    ".....kb....",
    ".....kb....",
    ".....kB....",
  ],
} satisfies Record<string, string[]>;

export type SpriteId = keyof typeof SPRITES;
